version: '3'
services:
  web:
    image: nginx
    ports:
      - "127.0.0.1:${HOST_PORT}:80"
    restart: always
    volumes:
      - public_content:/usr/share/nginx/html
    depends_on:
      - generator
  generator:
    build: .
    command: /app/launch.sh
    volumes:
      - public_content:/app/_site
volumes:
  public_content:
